### ISSUE TITLE
Unable to view TGA and TIFF images

### ISSUE THREAD

**Issue by Giova84** [easymodo/qimgv#103]
As I attempt to open a TGA or TIFF image using qimgv, aren't displayed at all, and furthermore, instead of thumbnails I get these symbols with a red X:
https://i.ibb.co/5MrcpG7/qimgv-TGA-error.png

Samples of TGA and TIFF images are available here:
http://netghost.narod.ru/gff/sample/images/tga/index.htm
http://netghost.narod.ru/gff/sample/images/tiff/index.htm

I am running Manjaro Linux, XFCE.

**Comment by easymodo** [comment]
Are you sure those tiff images are not corrupted?  I couldn't open them in gwenview either, and they look kinda sketchy when loaded in gimp  [https://i.imgur.com/Qk7rgTy.jpg](https://i.imgur.com/Qk7rgTy.jpg)

**Comment by easymodo** [comment]
I also just tried the ones from here  [http://www.fileformat.info/format/tiff/sample/](http://www.fileformat.info/format/tiff/sample/) and they open fine

**Comment by Giova84** [comment]
Hi, such files aren't certainly corrupted, since I am able to open them also with the simplest Viewnior image viewer: https://i.ibb.co/4JhjG9H/Viewnior.png
I also have other TGA and TIFF file (which I can't upload) which acts the same in qimgv.

**Comment by DaarkWel** [comment]
I also tried files from here ( http://www.fileformat.info/format/tiff/sample/) and qimgv doesn't open them. And it doesn't open any TIFFs that I tried - even just created with GIMP. Geeqie opens TIFFs just all right.

Archlinux, qimgv-git v0.8.8.r1.gdc59675-1.

**Comment by easymodo** [comment]
Fixed. Rebuild from aur and it should work

**Comment by Giova84** [comment]
Hi, I rebuilt qimgv from AUR, but qimgv is still unable to open such TGA file: http://netghost.narod.ru/gff/sample/images/tga/flag_b16.tga

viewnior, instead, is able to open and display such file.

**Comment by easymodo** [comment]
It should work. Make sure you've installed `qimgv-git` package, not the outdated one

**Comment by Giova84** [comment]
Sure: I've rebuilt qimgv-git, to be specific, on the repo I have `qimgv-git  v0.8.8.r12.g6e84931-1`

**Comment by easymodo** [comment]
Heh now I know why it worked for me. Install `kimageformats`. It's in repos (no kde dependencies).

**Comment by easymodo** [comment]
reopening until builtin support is done

**Comment by Giova84** [comment]
Installing `kimageformats` did the trick, thanks.
