### ISSUE TITLE
[BUG] version 1.0.0 breaks mouse scroll for prev/next image for Asus Gladius 2 wireless

### ISSUE THREAD

**Issue by ragouel** [easymodo/qimgv#337]
Prev/Next image scroll doesn't work, Zoom In/Out does.

OS: Arch Linux, latest as of 24/09/2021

**Comment by easymodo** [comment]
I dont remember touching anything mouse input-related..

Do you have this enabled per chance? Set it back to "Touchpad"  (just tried with my cheapo mouse on arch, wheel works)

Or try resetting shortcuts if that didnt help

![image](https://user-images.githubusercontent.com/5484275/134725112-d8dbd77f-bbaa-48a8-bc2d-5a96d3b949b1.png)

**Comment by ragouel** [comment]
Yes, I tried both. Nothing worked.

**Comment by easymodo** [comment]
found a possible culprit, could you please do a rebuild?

**Comment by ragouel** [comment]
It didn't work. I do, however, get the following on each scroll

`pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)
pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)
pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)
pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)
pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)
pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)
pixelDelta: QPoint(0,120) angleDelta: QPoint(0,120)`

**Comment by easymodo** [comment]
should be working again
blame the latest `libinput` update

**Comment by ragouel** [comment]
Yep, works now. 
Thank you.

**Comment by allanlaal** [comment]
still present in 1.0.2

I'll take a look when I get a chance

slava ukraini!

**Comment by ferroson** [comment]
> I dont remember touching anything mouse input-related..
> 
> Do you have this enabled per chance? Set it back to "Touchpad" (just tried with my cheapo mouse on arch, wheel works)
> 
> Or try resetting shortcuts if that didnt help
> 
> ![image](https://user-images.githubusercontent.com/5484275/134725112-d8dbd77f-bbaa-48a8-bc2d-5a96d3b949b1.png)

I have the same problem in Archcraft, touchpad scroll for next and image preview doesn't work, but Ctrl+toucpad scroll can zoom in and out image. The interesting thing, touchpad scroll sometimes works on video and audio files. So it seems it just doesn't work on the image. I used this version of qimgv: chaotic-aur/qimgv-git v1.0.3.alpha.r39.gcfed4cb-1

**Comment by bitzcoder** [comment]
Still having the same problem with libinput v1.22.1

**Comment by easymodo** [comment]
Pushed a workaround, **turn this off** and your wheel should work

![w](https://user-images.githubusercontent.com/5484275/230379742-88383735-4c31-456b-9a62-8872e5d7c963.jpg)

**Comment by roger21** [comment]
hello, so i have this bug on debian 12 (the mouse scroll does not prev/next the images) and i tried compiling the current master (it compiles fine) and then i unchecked that new option ...

what it does now is each notch of the wheel jumps 5 pictures at once -_-'

(also there is a bug on the display of the select just above, the M is not there, its fine once it is selected:
![Screenshot_2023-06-19_14-06-16](https://github.com/easymodo/qimgv/assets/892186/20b4112f-526c-43f3-9029-62373c0a9ed0))

**Comment by roger21** [comment]
i also tried installing libinput 1.23 from testing (it's 1.22 on stable) (libinput-bin and libinput10)

but 1.0.3 behave the same (doesn't work if checked, jump 5 if unchecked) (and 1.0.2 doesn't change either, doesn't work)

anyway for now i'm back to stable 1.0.2 (and libinput stable too) and i use imwheel to convert up and down (scroll) to left and right in qimgv

**Comment by roger21** [comment]
ok so ... it is the "[HighResolutionWheelScrolling](https://man.archlinux.org/man/libinput.4.en#Option~9)" option of libinput that messes everything up

creating the basic file in `/etc/X11/xorg.conf.d/30-libinput.conf` to disable it fix it all
```
Section "InputClass"
        Identifier "my mice"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Option "HighResolutionWheelScrolling" "false"
        Driver "libinput"
EndSection
```

with that 1.0.2 works fine with the scroll and 1.0.3 works fine too with or without checking the new option
